//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPMSBTenderReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="FPMSBTenderReference.ZWS_EPROC_VNDR")]
    public interface ZWS_EPROC_VNDR
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_EPROC_VNDR:ZEPROC_VNDRRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FPMSBTenderReference.ZEPROC_VNDRResponse1> ZEPROC_VNDRAsync(FPMSBTenderReference.ZEPROC_VNDRRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZEPROC_VNDR
    {
        
        private string nEW_VENDORField;
        
        private ZREQ_HEADER rQ_HEADERField;
        
        private ZREQ_VENDOR rQ_VENDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NEW_VENDOR
        {
            get
            {
                return this.nEW_VENDORField;
            }
            set
            {
                this.nEW_VENDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZREQ_HEADER RQ_HEADER
        {
            get
            {
                return this.rQ_HEADERField;
            }
            set
            {
                this.rQ_HEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ZREQ_VENDOR RQ_VENDOR
        {
            get
            {
                return this.rQ_VENDORField;
            }
            set
            {
                this.rQ_VENDORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZREQ_HEADER
    {
        
        private string rEQUEST_IDField;
        
        private string rEQ_TRANSACTION_IDField;
        
        private string cONSUMER_IDField;
        
        private string rEQ_TIMESTAMPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string REQUEST_ID
        {
            get
            {
                return this.rEQUEST_IDField;
            }
            set
            {
                this.rEQUEST_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string REQ_TRANSACTION_ID
        {
            get
            {
                return this.rEQ_TRANSACTION_IDField;
            }
            set
            {
                this.rEQ_TRANSACTION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONSUMER_ID
        {
            get
            {
                return this.cONSUMER_IDField;
            }
            set
            {
                this.cONSUMER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string REQ_TIMESTAMP
        {
            get
            {
                return this.rEQ_TIMESTAMPField;
            }
            set
            {
                this.rEQ_TIMESTAMPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZREQ_RETURN
    {
        
        private string rESPONSE_IDField;
        
        private string rES_TRANSACTION_IDField;
        
        private string pROVIDER_IDField;
        
        private string rES_TIMESTAMPField;
        
        private string rES_STATUSField;
        
        private string vNDR_NOField;
        
        private string mSG_CODEField;
        
        private string mSG_DESCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RESPONSE_ID
        {
            get
            {
                return this.rESPONSE_IDField;
            }
            set
            {
                this.rESPONSE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RES_TRANSACTION_ID
        {
            get
            {
                return this.rES_TRANSACTION_IDField;
            }
            set
            {
                this.rES_TRANSACTION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PROVIDER_ID
        {
            get
            {
                return this.pROVIDER_IDField;
            }
            set
            {
                this.pROVIDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RES_TIMESTAMP
        {
            get
            {
                return this.rES_TIMESTAMPField;
            }
            set
            {
                this.rES_TIMESTAMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RES_STATUS
        {
            get
            {
                return this.rES_STATUSField;
            }
            set
            {
                this.rES_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string VNDR_NO
        {
            get
            {
                return this.vNDR_NOField;
            }
            set
            {
                this.vNDR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MSG_CODE
        {
            get
            {
                return this.mSG_CODEField;
            }
            set
            {
                this.mSG_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MSG_DESC
        {
            get
            {
                return this.mSG_DESCField;
            }
            set
            {
                this.mSG_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZREQ_VENDOR
    {
        
        private string lIFNRField;
        
        private string bUKRSField;
        
        private string eKORGField;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string sORT1Field;
        
        private string sORT2Field;
        
        private string sTREETField;
        
        private string sTR_SUPPL3Field;
        
        private string lOCATIONField;
        
        private string dISTRICTField;
        
        private string pOSTL_COD1Field;
        
        private string cITYField;
        
        private string cOUNTRYField;
        
        private string rEGIONField;
        
        private string tELEPHONEField;
        
        private string fAX_NOField;
        
        private string e_MAILField;
        
        private string sTCD1Field;
        
        private string sTCD2Field;
        
        private string sTCD3Field;
        
        private string sTCD4Field;
        
        private string j_1KFTINDField;
        
        private string bAHNSField;
        
        private string fITYPField;
        
        private string tIN_NUMBERField;
        
        private string bANKSField;
        
        private string bANKLField;
        
        private string bANKNField;
        
        private string kOINHField;
        
        private string bVTYPField;
        
        private string bKREFField;
        
        private string aKONTField;
        
        private string zUAWAField;
        
        private string fDGRVField;
        
        private string zTERM_COMPANYField;
        
        private string zWELSField;
        
        private string rEPRFField;
        
        private string wAERSField;
        
        private string zTERMField;
        
        private string kALSKField;
        
        private string wEBREField;
        
        private string lEBREField;
        
        private string zSETTLRField;
        
        private string zKBDGField;
        
        private string zSBDGField;
        
        private string zACTVTField;
        
        private string zSJLNField;
        
        private string zDATSTField;
        
        private string zDATENField;
        
        private string zLOCField;
        
        private string zDATDFField;
        
        private string zDATRNField;
        
        private string zDATBLField;
        
        private string zDATBLNField;
        
        private string zKSYKTField;
        
        private string zRSBLField;
        
        private string bRSCHField;
        
        private string kTOKKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LIFNR
        {
            get
            {
                return this.lIFNRField;
            }
            set
            {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BUKRS
        {
            get
            {
                return this.bUKRSField;
            }
            set
            {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EKORG
        {
            get
            {
                return this.eKORGField;
            }
            set
            {
                this.eKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NAME1
        {
            get
            {
                return this.nAME1Field;
            }
            set
            {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NAME2
        {
            get
            {
                return this.nAME2Field;
            }
            set
            {
                this.nAME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SORT1
        {
            get
            {
                return this.sORT1Field;
            }
            set
            {
                this.sORT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SORT2
        {
            get
            {
                return this.sORT2Field;
            }
            set
            {
                this.sORT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STREET
        {
            get
            {
                return this.sTREETField;
            }
            set
            {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string STR_SUPPL3
        {
            get
            {
                return this.sTR_SUPPL3Field;
            }
            set
            {
                this.sTR_SUPPL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string LOCATION
        {
            get
            {
                return this.lOCATIONField;
            }
            set
            {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DISTRICT
        {
            get
            {
                return this.dISTRICTField;
            }
            set
            {
                this.dISTRICTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string POSTL_COD1
        {
            get
            {
                return this.pOSTL_COD1Field;
            }
            set
            {
                this.pOSTL_COD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string TELEPHONE
        {
            get
            {
                return this.tELEPHONEField;
            }
            set
            {
                this.tELEPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string FAX_NO
        {
            get
            {
                return this.fAX_NOField;
            }
            set
            {
                this.fAX_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string E_MAIL
        {
            get
            {
                return this.e_MAILField;
            }
            set
            {
                this.e_MAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string STCD1
        {
            get
            {
                return this.sTCD1Field;
            }
            set
            {
                this.sTCD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string STCD2
        {
            get
            {
                return this.sTCD2Field;
            }
            set
            {
                this.sTCD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string STCD3
        {
            get
            {
                return this.sTCD3Field;
            }
            set
            {
                this.sTCD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string STCD4
        {
            get
            {
                return this.sTCD4Field;
            }
            set
            {
                this.sTCD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string J_1KFTIND
        {
            get
            {
                return this.j_1KFTINDField;
            }
            set
            {
                this.j_1KFTINDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string BAHNS
        {
            get
            {
                return this.bAHNSField;
            }
            set
            {
                this.bAHNSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string FITYP
        {
            get
            {
                return this.fITYPField;
            }
            set
            {
                this.fITYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string TIN_NUMBER
        {
            get
            {
                return this.tIN_NUMBERField;
            }
            set
            {
                this.tIN_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string BANKS
        {
            get
            {
                return this.bANKSField;
            }
            set
            {
                this.bANKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string BANKL
        {
            get
            {
                return this.bANKLField;
            }
            set
            {
                this.bANKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string BANKN
        {
            get
            {
                return this.bANKNField;
            }
            set
            {
                this.bANKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string KOINH
        {
            get
            {
                return this.kOINHField;
            }
            set
            {
                this.kOINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string BVTYP
        {
            get
            {
                return this.bVTYPField;
            }
            set
            {
                this.bVTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string BKREF
        {
            get
            {
                return this.bKREFField;
            }
            set
            {
                this.bKREFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string AKONT
        {
            get
            {
                return this.aKONTField;
            }
            set
            {
                this.aKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string ZUAWA
        {
            get
            {
                return this.zUAWAField;
            }
            set
            {
                this.zUAWAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string FDGRV
        {
            get
            {
                return this.fDGRVField;
            }
            set
            {
                this.fDGRVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string ZTERM_COMPANY
        {
            get
            {
                return this.zTERM_COMPANYField;
            }
            set
            {
                this.zTERM_COMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string ZWELS
        {
            get
            {
                return this.zWELSField;
            }
            set
            {
                this.zWELSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string REPRF
        {
            get
            {
                return this.rEPRFField;
            }
            set
            {
                this.rEPRFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string WAERS
        {
            get
            {
                return this.wAERSField;
            }
            set
            {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string ZTERM
        {
            get
            {
                return this.zTERMField;
            }
            set
            {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string KALSK
        {
            get
            {
                return this.kALSKField;
            }
            set
            {
                this.kALSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string WEBRE
        {
            get
            {
                return this.wEBREField;
            }
            set
            {
                this.wEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string LEBRE
        {
            get
            {
                return this.lEBREField;
            }
            set
            {
                this.lEBREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string ZSETTLR
        {
            get
            {
                return this.zSETTLRField;
            }
            set
            {
                this.zSETTLRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string ZKBDG
        {
            get
            {
                return this.zKBDGField;
            }
            set
            {
                this.zKBDGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string ZSBDG
        {
            get
            {
                return this.zSBDGField;
            }
            set
            {
                this.zSBDGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string ZACTVT
        {
            get
            {
                return this.zACTVTField;
            }
            set
            {
                this.zACTVTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string ZSJLN
        {
            get
            {
                return this.zSJLNField;
            }
            set
            {
                this.zSJLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string ZDATST
        {
            get
            {
                return this.zDATSTField;
            }
            set
            {
                this.zDATSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string ZDATEN
        {
            get
            {
                return this.zDATENField;
            }
            set
            {
                this.zDATENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string ZLOC
        {
            get
            {
                return this.zLOCField;
            }
            set
            {
                this.zLOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string ZDATDF
        {
            get
            {
                return this.zDATDFField;
            }
            set
            {
                this.zDATDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string ZDATRN
        {
            get
            {
                return this.zDATRNField;
            }
            set
            {
                this.zDATRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string ZDATBL
        {
            get
            {
                return this.zDATBLField;
            }
            set
            {
                this.zDATBLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string ZDATBLN
        {
            get
            {
                return this.zDATBLNField;
            }
            set
            {
                this.zDATBLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string ZKSYKT
        {
            get
            {
                return this.zKSYKTField;
            }
            set
            {
                this.zKSYKTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string ZRSBL
        {
            get
            {
                return this.zRSBLField;
            }
            set
            {
                this.zRSBLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string BRSCH
        {
            get
            {
                return this.bRSCHField;
            }
            set
            {
                this.bRSCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string KTOKK
        {
            get
            {
                return this.kTOKKField;
            }
            set
            {
                this.kTOKKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZEPROC_VNDRResponse
    {
        
        private ZREQ_RETURN rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZREQ_RETURN RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZEPROC_VNDRRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public FPMSBTenderReference.ZEPROC_VNDR ZEPROC_VNDR;
        
        public ZEPROC_VNDRRequest()
        {
        }
        
        public ZEPROC_VNDRRequest(FPMSBTenderReference.ZEPROC_VNDR ZEPROC_VNDR)
        {
            this.ZEPROC_VNDR = ZEPROC_VNDR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZEPROC_VNDRResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public FPMSBTenderReference.ZEPROC_VNDRResponse ZEPROC_VNDRResponse;
        
        public ZEPROC_VNDRResponse1()
        {
        }
        
        public ZEPROC_VNDRResponse1(FPMSBTenderReference.ZEPROC_VNDRResponse ZEPROC_VNDRResponse)
        {
            this.ZEPROC_VNDRResponse = ZEPROC_VNDRResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ZWS_EPROC_VNDRChannel : FPMSBTenderReference.ZWS_EPROC_VNDR, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ZWS_EPROC_VNDRClient : System.ServiceModel.ClientBase<FPMSBTenderReference.ZWS_EPROC_VNDR>, FPMSBTenderReference.ZWS_EPROC_VNDR
    {
        
        public ZWS_EPROC_VNDRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FPMSBTenderReference.ZEPROC_VNDRResponse1> FPMSBTenderReference.ZWS_EPROC_VNDR.ZEPROC_VNDRAsync(FPMSBTenderReference.ZEPROC_VNDRRequest request)
        {
            return base.Channel.ZEPROC_VNDRAsync(request);
        }
        
        public System.Threading.Tasks.Task<FPMSBTenderReference.ZEPROC_VNDRResponse1> ZEPROC_VNDRAsync(FPMSBTenderReference.ZEPROC_VNDR ZEPROC_VNDR)
        {
            FPMSBTenderReference.ZEPROC_VNDRRequest inValue = new FPMSBTenderReference.ZEPROC_VNDRRequest();
            inValue.ZEPROC_VNDR = ZEPROC_VNDR;
            return ((FPMSBTenderReference.ZWS_EPROC_VNDR)(this)).ZEPROC_VNDRAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
